"""Update league member budget default to 50M

Revision ID: 5ccb68ebcfcf
Revises: ad08b216abaa
Create Date: 2026-02-06 18:16:34.763218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ccb68ebcfcf'
down_revision: Union[str, Sequence[str], None] = 'ad08b216abaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
