"""add_performance_indexes

Revision ID: ad08b216abaa
Revises: d91bbfe4c38c
Create Date: 2026-02-05 18:57:11.356658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'ad08b216abaa'
down_revision: Union[str, Sequence[str], None] = 'd91bbfe4c38c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def index_exists(bind, table_name, index_name):
    insp = inspect(bind)
    indexes = insp.get_indexes(table_name)
    return any(idx['name'] == index_name for idx in indexes)

def column_exists(bind, table_name, column_name):
    insp = inspect(bind)
    columns = insp.get_columns(table_name)
    return any(col['name'] == column_name for col in columns)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    
    # ### commands auto generated by Alembic - please adjust! ###
    
    # LEAGUE MEMBERS
    if not index_exists(bind, 'leagues_members', 'ix_leagues_members_league_id'):
        with op.batch_alter_table('leagues_members', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_leagues_members_league_id'), ['league_id'], unique=False)

    # MATCHES
    with op.batch_alter_table('matches', schema=None) as batch_op:
        if not index_exists(bind, 'matches', 'idx_match_status'):
            batch_op.create_index('idx_match_status', ['status'], unique=False)
        
        if not index_exists(bind, 'matches', 'idx_match_status_processed'):
            batch_op.create_index('idx_match_status_processed', ['status', 'is_processed'], unique=False)
            
        if not index_exists(bind, 'matches', 'ix_matches_team_a_id'):
            batch_op.create_index(batch_op.f('ix_matches_team_a_id'), ['team_a_id'], unique=False)
            
        if not index_exists(bind, 'matches', 'ix_matches_team_b_id'):
            batch_op.create_index(batch_op.f('ix_matches_team_b_id'), ['team_b_id'], unique=False)

    # PLAYERS
    with op.batch_alter_table('players', schema=None) as batch_op:
        if not column_exists(bind, 'players', 'photo_url'):
            batch_op.add_column(sa.Column('photo_url', sa.String(length=512), nullable=True))
            
        if not index_exists(bind, 'players', 'idx_player_region'):
            batch_op.create_index('idx_player_region', ['region'], unique=False)
            
        if not index_exists(bind, 'players', 'idx_player_role'):
            batch_op.create_index('idx_player_role', ['role'], unique=False)

    # ROSTERS
    if not index_exists(bind, 'rosters', 'ix_rosters_league_member_id'):
        with op.batch_alter_table('rosters', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_rosters_league_member_id'), ['league_member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rosters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rosters_league_member_id'))

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index('idx_player_role')
        batch_op.drop_index('idx_player_region')
        batch_op.drop_column('photo_url')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_team_b_id'))
        batch_op.drop_index(batch_op.f('ix_matches_team_a_id'))
        batch_op.drop_index('idx_match_status_processed')
        batch_op.drop_index('idx_match_status')

    with op.batch_alter_table('leagues_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leagues_members_league_id'))

    # ### end Alembic commands ###
