"""Add unique constraints and performance indexes

Revision ID: d91bbfe4c38c
Revises: 
Create Date: 2026-01-28 16:34:48.190581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91bbfe4c38c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues_members', schema=None) as batch_op:
        batch_op.create_index('idx_team_name', ['team_name'], unique=False)
        batch_op.create_unique_constraint('uq_league_user', ['league_id', 'user_id'])

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('idx_match_date', ['date'], unique=False)

    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_player_match_stats', ['player_id', 'match_id'])

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index('idx_player_name', ['name'], unique=False)

    with op.batch_alter_table('price_history_player', schema=None) as batch_op:
        batch_op.create_index('idx_price_history_date', ['date'], unique=False)

    with op.batch_alter_table('rosters', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_roster_player', ['league_member_id', 'player_id'])

    with op.batch_alter_table('user_points_history', schema=None) as batch_op:
        batch_op.create_index('idx_points_history_date', ['recorded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_points_history', schema=None) as batch_op:
        batch_op.drop_index('idx_points_history_date')

    with op.batch_alter_table('rosters', schema=None) as batch_op:
        batch_op.drop_constraint('uq_roster_player', type_='unique')

    with op.batch_alter_table('price_history_player', schema=None) as batch_op:
        batch_op.drop_index('idx_price_history_date')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index('idx_player_name')

    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.drop_constraint('uq_player_match_stats', type_='unique')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('idx_match_date')

    with op.batch_alter_table('leagues_members', schema=None) as batch_op:
        batch_op.drop_constraint('uq_league_user', type_='unique')
        batch_op.drop_index('idx_team_name')

    # ### end Alembic commands ###
