from enum import Enum

class ErrorCode(str, Enum):
    # General
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    
    # User
    USER_NOT_FOUND = "USER_NOT_FOUND"
    EMAIL_DUPLICATED = "EMAIL_DUPLICATED"
    USERNAME_DUPLICATED = "USERNAME_DUPLICATED"
    INVALID_PASSWORD = "INVALID_PASSWORD"
    EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND"
    
    # Fantasy Business Logic
    LEAGUE_FULL = "LEAGUE_FULL"
    ALREADY_IN_LEAGUE = "ALREADY_IN_LEAGUE"
    INSUFFICIENT_BUDGET = "INSUFFICIENT_BUDGET"
    ROSTER_LIMIT_REACHED = "ROSTER_LIMIT_REACHED"
    PLAYER_ALREADY_IN_ROSTER = "PLAYER_ALREADY_IN_ROSTER"
    SAME_TEAM_LIMIT_REACHED = "SAME_TEAM_LIMIT_REACHED"
    ROLE_LIMIT_REACHED = "ROLE_LIMIT_REACHED"
    NOT_FOUND = "NOT_FOUND"
    FORBIDDEN = "FORBIDDEN"
    DUPLICATED = "DUPLICATED"
    INVALID_INPUT = "INVALID_INPUT"